namespace CnV.GameData
{
	public class Errors
	{
		public static string[] s = {
/* 0: */ null, // 0 indexed
/* 1: */ "Error number 1!",
/* 2: */ "Error number 2!",
/* 3: */ "Error number 3!",
/* 4: */ "Error number 4!",
/* 5: */ "Error number 5!",
/* 6: */ "Error number 6!",
/* 7: */ "You do not have the title to use this item!",
/* 8: */ "You must enter a value!",
/* 9: */ "You do not have enough charisma!",
/* 10: */ "You do not have enough denari!",
/* 11: */ "You do not have enough wood!",
/* 12: */ "You do not have enough stone!",
/* 13: */ "You do not have enough iron!",
/* 14: */ "You do not have enough food!",
/* 15: */ "You do not have enough gold!",
/* 16: */ "You do not have enough troop space!",
/* 17: */ "Your rank is not high enough for this number of Senators!",
/* 18: */ "Your Build Queue is full!",
/* 19: */ "Upgrade your Basillica for more building spots!",
/* 20: */ "Your Basillica level is not high enough for this building!",
/* 21: */ "You cannot send negative Resources!",
/* 22: */ "Cart Capacity too low!",
/* 23: */ "Ship Capacity too low!",
/* 24: */ "You have no available transport in this city!",
/* 25: */ "You do not have any Carts!",
/* 26: */ "You do not have any Ships!",
/* 27: */ "You cannot send to the same city!",
/* 28: */ "Both Cities Need to be on water!",
/* 29: */ "Carts cannot swim!",
/* 30: */ "Your Rank is too low!",
/* 31: */ "You cannot demolish your Basillica!",
/* 32: */ "You cannot demolish a Castle!",
/* 33: */ "No Command Slots available!",
/* 34: */ "The selected coordinates are not a valid target.!",
/* 35: */ "You do not have the selected troops!",
/* 36: */ "You cannot reinforce the same city!",
/* 37: */ "You do not have enough carts!",
/* 38: */ "You do not have enough ships!",
/* 39: */ "The target is not on water!",
/* 40: */ "You do not have enough Senators!",
/* 41: */ "You cannot send negative troops!",
/* 42: */ "Your Rank is not high enough!",
/* 43: */ "You do not have enough troops!",
/* 44: */ "You must have a castle to attack!",
/* 45: */ "You cannot attack yourself!",
/* 46: */ "You cannot send a naval attack to this target!",
/* 47: */ "You cannot assault a city!",
/* 48: */ "You cannot siege a city!",
/* 49: */ "Stop hitting yourself!!!!",
/* 50: */ "You cannot reinforce others right now!",
/* 51: */ "You cannot send resources to others right now!",
/* 52: */ "You must enter a value!",
/* 53: */ "You do not have enough troops!",
/* 54: */ "You cannot send resources to others right now!",
/* 55: */ "This city is under siege!",
/* 56: */ "Can't leave an alliance during this contest!",
/* 57: */ "Can't boot a member during this contest!",
/* 58: */ "You cant attack someone in your alliance!",
/* 59: */ "You must send scouts to scout someone!",
/* 60: */ "Target is not valid!",
/* 61: */ "You cannot send sieges on a plunder!",
/* 62: */ "You do not have enough Galley space!",
/* 63: */ "You Must Enter an Hour!",
/* 64: */ "You Must Enter an Minute!",
/* 65: */ "You Must Enter an Second!",
/* 66: */ "You Must Enter an Day!",
/* 67: */ "This time is in the past!",
/* 68: */ "Your Troops cannot make this time!",
/* 69: */ "Do not bite the GMs. They bite back!",
/* 70: */ "This feature is not ready yet!",
/* 71: */ "You do not have enough move spots!",
/* 72: */ "Your Rank is not high enough for more cities!",
/* 73: */ "Command Slots are Full!",
/* 74: */ "This Boss is on water, send ships!",
/* 75: */ "This Dungeon is on water, send ships!",
/* 76: */ "You must save before you can edit another!",
/* 77: */ "Finish editing before you save!",
/* 78: */ "Select a valid trade!",
/* 79: */ "Only one item per trade command allowed!",
/* 80: */ "This is not a valid target!",
/* 81: */ "This dungeon is abandoned!",
/* 82: */ "Palaces need a clear 3x3 area to build!",
/* 83: */ "A city can only have 1 Palace!",
/* 84: */ "This city is not blessed!",
/* 85: */ "You are already building a Temple!",
/* 86: */ "The target is not currently Blessed!",
/* 87: */ "Your alliance does not have enough faith!",
/* 88: */ "Your Troops will not return in time!",
/* 89: */ "You do not have enough Portalstones!",
/* 90: */ "War Councillor must be active to set future attacks!",
/* 91: */ "War Councillor must be active to set recurring raids!",
/* 92: */ "Please Enter a valid ShareString!",
/* 93: */ "You must send the minimum troop strength!",
/* 94: */ "You do not have permission!",
/* 95: */ "You do not have enough resources!",
/* 96: */ "The requested amount in invalid for this offer!",
/* 97: */ "This offer is no longer available!",
/* 98: */ "You can only be subbed by one person at a time!",
/* 99: */ "This player does not exist!",
/* 100: */ "You cannot abandon your last city!",
/* 101: */ "Enter a valid key, or request a new one!",
/* 102: */ "You cannot currently abandon any more cities!",
/* 103: */ "Build Councillor is not active!",
/* 104: */ "Build Councillor cannot queue this building!",
/* 105: */ "You can only have 100 buildings in a city!",
/* 106: */ "You do not have this many items!",
/* 107: */ "You cannot quit as Leader!",
/* 108: */ "You cannot remove yourself!",
/* 109: */ "You must promote another leader!",
/* 110: */ "You cannot reset while in an alliance!",
/* 111: */ "This building has already been paid for!",
/* 112: */ "You must convert lower levels first!",
/* 113: */ "You cannot queue Senators with Councillors!",
/* 114: */ "You must enter a max travel time!",
/* 115: */ "Item can only be used on a resource node!",
/* 116: */ "You must select a valid command!",
/* 117: */ "This building is already fully built!",
/* 118: */ "Nothing there to upgrade!",
/* 119: */ "You have more than 100 buildings, demolish some!",
/* 120: */ "You do not have enough galleys for this troop amount!",
/* 121: */ "You must send ships to different continents!",
/* 122: */ "This boss is on a different continent!",
/* 123: */ "You cannot send ships to a land boss!",
/* 124: */ "You cannot send a boss raid for the future!",
/* 125: */ "You cannot move a building while upgrading/downgrading!",
/* 126: */ "You cannot move your Basillica!",
/* 127: */ "There is no building to move!",
/* 128: */ "You cannot move a resource node!",
/* 129: */ "This building cannot be moved here!",
/* 130: */ "There is already a building here!",
/* 131: */ "Substitutes cannot send Resources",
/* 132: */ "You Must Select a List to Edit",
/* 133: */ "You are under new player protection",
/* 134: */ "Target is under new player protection",
/* 135: */ "You can only have 10 saved configuations",
/* 136: */ "You must select a preset",
/* 137: */ "Request minimum must be lower than Send",
/* 138: */ "You do not have the title for this amount",
/* 139: */ "No trades to alliance for 20 days after start",
/* 140: */ "No trades to others for 30 days after start",
/* 141: */ "You can only have one of these items active at a time",
/* 142: */ "You can not complete this action while under protection",
/* 143: */ "This player is under protection",
/* 144: */ "This is not a valid name",
/* 145: */ "You can only substitute one player at a time!",
/* 146: */ "This building can only be built on water!",
/* 147: */ "This building cannot be built on water!",
/* 148: */ "Only Post towers can be built on inner walls!",
/* 149: */ "Only towers can be built on walls!",
/* 150: */ "Towers can only be built on walls!",
/* 151: */ "Barracade towers can only be built on outer walls!",
/* 152: */ "There is already a building on this spot!",
/* 153: */ "You have not been playing long enough for a substitute!",
/* 154: */ "You do not have permission!",
/* 155: */ "Alliance is already full!",
/* 156: */ "Player is already in the alliance!",
/* 157: */ "You cant invite yourself!",
/* 158: */ "Player does not exist!",
/* 159: */ "Temples cannot be moved!",
/* 160: */ "Temple donations cannot be made without a Blessing",
/* 161: */ "Substitutes cannot make trades!",
/* 162: */ "Player has already been invited!",
/* 163: */ "City Names can only be 16 characters long!"
		};
	}
}
